---
title: "Basics of R for Data Science"
subtitle: "PhD Course in Psychological Sciences - University of Padova"
author: "<a href='https://enricotoffalini.github.io/' target='blank'>Enrico Toffalini</a>"
include-in-header: assets/header.html
format: 
  html:
    self-contained: true
    toc: true   
    toc-depth: 3 
    toc-expand: 3 
    code-fold: false 
    message: false
    css: "assets/custom.css"
editor: visual
---

## About This Course

This is a short (10 hours) introductory course on [**R**](https://www.r-project.org/){target="_blank"} that is offered within the [*PhD program in Psychological Sciences*](https://phd.psy.unipd.it/){target="_blank"} *(University of Padova)*. The course is aimed to prepare students for many future methodological courses in this program, where R is used extensively. [**R**](https://www.r-project.org/){target="_blank"} is a high-level open-source programming language that is widely used in academic research, but also increasingly adopted in business for data science. It has a large ecosystem of libraries and tools that allow you to perform flexible and powerful data analysis. [**RStudio**](https://posit.co/download/rstudio-desktop/){target="_blank"} is a popular IDE *(Integrated Development Environment)* which provides an excellent environment for coding, visualization, and report generation when programming in R (and in other languages).

This online book is a useful additional resource for the present course: [***Introduction2R***](https://psicostat.github.io/Introduction2R_EN/){target="_blank"}

## Dates and Rooms

| Day                             | Time        | Room |
|---------------------------------|-------------|------|
| Monday, 10^th^ November 2025    | 10:30-12:30 | 4M   |
| Tuesday, 11^th^ November 2025   | 9:30-12:30  | 4M   |
| Wednesday, 12^th^ November 2025 | 9:30-12:30  | 4M   |
| Thursday, 13^th^ November 2025  | 8:30-10:30  | 4M   |

## Getting Started

1.  **Bookmark this course homepage** to have quick access to this material ([https://enricotoffalini.github.io/Basics-R/](https://enricotoffalini.github.io/Basics-R/){target="_blank"}).
2.  **Install R**: go to the official [R download page](https://cran.r-project.org/){target="_blank"} and follow the installation instructions for your operating system (further setup instructions can be found in [*Chapter 1*](https://psicostat.github.io/Introduction2R_EN/install.html){target="_blank"} of *Introduction2R*).
3.  **Install RStudio as the IDE** *(Integrated Development Environment)*: go to [the *RStudio Desktop* download page](https://posit.co/download/rstudio-desktop/){target="_blank"} to install the IDE on your computer. *(ALTERNATIVES: If you don't like RStudio or want to try something else have a look at [Positron](https://positron.posit.co/){target="_blank"} or [Jupyter notebook](https://jupyter.org/){target="_blank"}; for fully-online coding, have a look at [Posit.cloud](https://posit.cloud/){target="_blank"} or even [Google Colab](https://colab.research.google.com/){target="_blank"} setting R kernel).*
4.  **Test your local setup**: Make sure that you local R installation works. Open RStudio and run the following code in the console panel:

``` r
pkgs = c("readxl", "psych", "ggplot2")
install.packages(pkgs)
psych::fisherz(0.5)
rnorm(10)
```

## Course Topics

The goal of this short course is to make you proficient with the development environment, basic data structures, and essential concepts of programming in R. Advanced topics like statistical modelling and data simulation will be covered in future courses and are not presented here, although occasional simple examples may appear

#### Introduction to the R Environment and First Steps in R

Install R, manage work sessions in R Studio, create objects, understand data types and perform basic operations on them, import and export data, figures, and workspaces

#### Data Structures

Understand main data structures in R and interact with them effectively: vectors, matrices, dataframes, factors, lists. Manipulating data with dataframes will be given special attention

#### Basics of Programming in R

Understand essential programming concepts and their implementation in R: write conditional operations (e.g., `if...else`), run iterative programming (`for` and other loops; `*apply` family), define custom functions

#### *A bit more*

Some materials in the *Exercises section* below will provide more stimulating challenges even beyond the scope of the present introductory course, depending on the interest and the prior experience with R

## Materials

### Slides

-   [**Intro to This Course, Getting Started with R**](Slides/0.GettingStartedR.html){target="_blank"} - ([pdf](Slides/0.GettingStartedR.pdf){target="_blank"})
-   [**Basic Operations, Basic Types of Data**](Slides/1.1.FirstStepsR-1.html){target="_blank"} - ([pdf](Slides/1.1.FirstStepsR-1.pdf){target="_blank"})
-   [**Environment, Packages, Functions, Import/Export**](Slides/1.2.FirstStepsR-2.html){target="_blank"} - ([pdf](Slides/1.2.FirstStepsR-2.pdf){target="_blank"})
-   [**Data Structures: Vectors**](Slides/2.1.DataStruc-1.html){target="_blank"} - ([pdf](Slides/2.1.DataStruc-1.pdf){target="_blank"})
-   [**Data Structures: Data Frames**](Slides/2.2.DataStruc-2.html){target="_blank"} - ([pdf](Slides/2.2.DataStruc-2.pdf){target="_blank"})
-   [**Data Structures: Factors, Lists, Matrices, Arrays**](Slides/2.3.DataStruc-3.html){target="_blank"} - ([pdf](Slides/2.3.DataStruc-3.pdf){target="_blank"})
-   [**Basics of Programming: If...Else, Iterations, Custom Functions**](Slides/3.Programming.html){target="_blank"} - ([pdf](Slides/3.Programming.pdf){target="_blank"})

### Extra materials

*Have a look at these pages, and remember that they are here if you need them later:*

-   List of [**RStudio Shortcuts that Everyone Should Know**](Examples-Tutorials/TutorialShortcuts.html){target="_blank"}
-   Tutorial on [**files extensions (in Windows)**](Examples-Tutorials/TutorialExtensions.html){target="_blank"}

### Exercises

*— The following exercises are fundamental, and they importantly integrate concepts from the slides and introduce new functions and methods that you want to know!*

-   [**First steps in R**](Exercises/1-Exercises-First-steps.html){target="_blank"}
-   [**Vectors**](Exercises/2.1-Exercises-Vectors.html){target="_blank"}
-   [**Dataframes**](Exercises/2.2-Exercises-Dataframes.html){target="_blank"}
-   [**Basics of Programming... with some data science**](Exercises/3-Exercises-ProgrMore.html){target="_blank"}
-   [**Programming like a data scientist**](Exercises/4-Exercises-LikeDataScientist.html){target="_blank"}
-   [<b>The data <em>nightmare</em> exercise</b>](Exercises/5-Exercises-DataNightmare.html){target="_blank"}

*— These other exercises are beyond the scope of this introductory course, but they could be stimulating and useful for more advanced R users:*

-   [**Creating a word cloud**](Exercises/10-WordCloud.html){target="_blank"}
    -   ::: {style="font-size:14px;"}
        **see additional material on [Working With Strings](Examples-Tutorials/ExampleStrings.html){target="_blank"}**
        :::
-   [**Basics of Statistical Data Simulation in R**](Exercises/11-BasicsSimulations.html){target="_blank"}
-   [**Basics of Monte Carlo simulations for Power analysis**](Exercises/12-MonteCarloSim.html){target="_blank"}
-   [**Monte Carlo Power Simulation: Mixed-Effects Logistic Regression and Some Parallelization**](Exercises/13-MonteCarloLogistic.html){target="_blank"}

------------------------------------------------------------------------

::: {style="font-size:13px;"}
Other links:
:::

::: {.arrow-list style="font-size:11px; color:#555555"}
-   GitHub repo associated to the present course website: [https://github.com/EnricoToffalini/Basics-R](https://github.com/EnricoToffalini/Basics-R){target="_blank"}
-   Access <b><a href="https://padlet.com/enricotoffalini/basicsr-1msunv8lba3mqf5k" target="_blank">padlet</a></b> for questions of additional materials
-   Read a modest proposal for <a href="https://docs.google.com/document/d/1-2Ty2Sd1QQzCCFt3SZpz3hhRkM3XEdvf/" target="_blank">open source software in the PhD program in Psychological Sciences</a>
-   Thousands of thanks to <a href="https://filippogambarota.github.io/" target="_blank">Filippo Gambarota</a> for sharing his expertise in using GitHub and Quarto.
:::
